# Generated by Django 2.0.6 on 2018-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
