# Generated by Django 2.0.6 on 2018-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20180605_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='Lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
