# Generated by Django 2.0.6 on 2018-06-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_personas_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='CDC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='MotherLastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
