# Generated by Django 2.0.6 on 2018-06-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20180606_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='Gestor',
        ),
        migrations.AddField(
            model_name='personas',
            name='Gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Personas'),
        ),
    ]
