# Generated by Django 2.0.6 on 2018-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20180606_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='CDC',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
