# Generated by Django 2.0.6 on 2018-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20180607_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='Area',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='Puesto',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
